### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by d4rckh** [daanbreur/SwishandFrick#28]
### Is there an existing issue for this?

- [X] I have searched the existing issues and did not find any.

### Current Behavior

Test

### Expected Behavior

Xxx

### Steps To Reproduce

Xxx

### Screenshots?

Xd

### Logfiles?

Ccx

### Environment

```markdown
- **OS**: 
- **OS Version**: 
- **Python Version**: 
- **Game version**:
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](CODE_OF_CONDUCT.md)

**Comment by daanbreur** [comment]
thanks for testin
